version: "3.8"
services:
  finalproject-image:
    container_name: finalproject-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:


#      Local Server

      HOST: host.docker.internal
      PORT: 1433
      DB_NAME: "TAkhir"
      DB_UNAME: sa
      DB_PWD: 04314a220d233becd613f5d70d21dd78
      SHOW_SQL: "true"
      DDL_AUTO: update
      SCHEMA: dbo
      SVR_PORT: 8080

# How to start:
# docker-compose up --build

# change TAG:
# docker tag finalproject-finalproject-image corneliusps/finalproject:1.0